import { ScenarioParameter } from "@/app/simulation/components/ScenarioExplorer";

export const sampleScenarioParameters: ScenarioParameter[] = [
  {
    id: "retirementAge",
    name: "Retirement Age",
    description: "Age at which you plan to retire.",
    minValue: 60,
    maxValue: 75,
    stepSize: 1,
    unit: "years",
    defaultValue: 65,
  },
  {
    id: "savingsRate",
    name: "Annual Savings Rate",
    description: "Percentage of income saved for retirement each year.",
    minValue: 5,
    maxValue: 30,
    stepSize: 1,
    unit: "%",
    defaultValue: 15,
  },
  {
    id: "withdrawalRate",
    name: "Annual Withdrawal Rate",
    description: "Percentage of portfolio withdrawn annually during retirement.",
    minValue: 2,
    maxValue: 6,
    stepSize: 0.25,
    unit: "%",
    defaultValue: 4,
  },
  {
    id: "stockAllocation",
    name: "Stock Allocation",
    description: "Percentage of portfolio allocated to stocks vs. bonds.",
    minValue: 40,
    maxValue: 90,
    stepSize: 5,
    unit: "%",
    defaultValue: 60,
  },
  {
    id: "socialSecurityStartAge",
    name: "Social Security Start Age",
    description: "Age at which you begin collecting Social Security benefits.",
    minValue: 62,
    maxValue: 70,
    stepSize: 1,
    unit: "years",
    defaultValue: 67,
  },
];
